namespace CodeExercise.Core.Common
{
    public enum MessageCodeEnum
    {
        // Commonly used messages
        RECORDS_NOT_FOUND,
        RECORDS_MAX_ROW_COUNT,
        SYSTEM_FAILURE,
        SUCCESS,
        NOT_FOUND,

        // Tag related messages
        CREATE_TAG_SUCCESSFUL,
        TAG_NAME_EXIST,
        TAG_NAME_EMPTY_VALIDATE,
        TAG_NAME_LENGTH_VALIDATE,
        TAG_DISPLAYNAME_EMPTY_VALIDATE,
        TAG_DISPLAYNAME_LENGTH_VALIDATE,
        UPDATE_TAG_SUCCESSFUL,
        TAG_ID_NOT_EXIST_VALIDATE,

        // Problem related messages
        PROBLEM_TITLE_EMPTY_VALIDATE,
        PROBLEM_TITLE_MAX_LENGTH_VALIDATE,
        PROBLEM_TITLE_MIN_LENGTH_VALIDATE,
        PROBLEM_DESCRIPTION_EMPTY_VALIDATE,
        PROBLEM_TIME_LIMIT_INVALID,
        PROBLEM_MEMORY_LIMIT_INVALID,
        PROBLEM_TEMPLATE_CODE_EMPTY_VALIDATE,
        CREATE_PROBLEM_SUCCESSFUL,
        UPDATE_PROBLEM_SUCCESSFUL,
        DELETE_PROBLEM_SUCCESSFUL,
        PROBLEM_TAGS_EMPTY_VALIDATE,
        PROBLEM_TESTCASES_EMPTY_VALIDATE,
        PROBLEM_TAGS_DUPLICATE_VALIDATE,
        PROBLEM_TEMPLATE_CODE_LANGUAGE_DUPLICATE_VALIDATE,
        USER_TEMPLATE_CODE_EMPTY_VALIDATE,
        HIDDEN_TEMPLATE_CODE_EMPTY_VALIDATE,
        TEMPLATE_CODE_ALREADY_EXISTS,
        TEMPLATE_CODE_NOT_FOUND,
        LANGUAGE_ID_MISMATCH,
        INVALID_ACTION_FLAG,

        // Test case related messages
        TEST_CASE_INPUT_EMPTY_VALIDATE,
        TEST_CASE_OUTPUT_EMPTY_VALIDATE,
        TEST_CASE_INPUT_DISPLAY_EMPTY_VALIDATE,
        TEST_CASE_OUTPUT_DISPLAY_EMPTY_VALIDATE,
        TEST_CASE_INVALID_REFERENCE,

        // Template code related messages
        TEMPLATE_CODE_EMPTY_VALIDATE,
        TEMPLATE_CODE_INVALID_REFERENCE,

        // Programming language related messages
        PROGRAMMING_LANGUAGE_ID_NOT_EXIST_VALIDATE
    }
}
